export const BINANCE_BUY_ORDERS = 'BINANCE_BUY_ORDERS';
export const BINANCE_SELL_ORDERS = 'BINANCE_SELL_ORDERS';
export const OKX_BUY_ORDERS = 'OKX_BUY_ORDERS';
export const OKX_SELL_ORDERS = 'OKX_SELL_ORDERS';
