import { BINANCE_SYMBOLS, OKX_SYMBOLS } from '~core/constants/crypto-code.constant';

export const BINANCE_MONITOR_SYMBOLS = [BINANCE_SYMBOLS.BTCUSDT, BINANCE_SYMBOLS.ETHUSDT, BINANCE_SYMBOLS.SOLUSDT];
export const OKX_MONITOR_SYMBOLS = [OKX_SYMBOLS.BTCUSDT, OKX_SYMBOLS.ETHUSDT, OKX_SYMBOLS.SOLUSDT];

export const BUY_DIP_PERCENTAGES = [8, 12, 17, 23, 30, 38, 47, 57];
